import type { Metadata } from "next";
import { Jost } from "next/font/google";
import Providers from "./Provider";
import './globals.css';

const jost = Jost({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],

});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="">
      <body className={`${jost.className} bg-bg-dark text-text antialiased max-w-[1440px] mx-auto mt-0 md:my-4 border-0 border-text-muted/10 md:border md:rounded-xl`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
